config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|hu/ do
    resources :posts, only: [:index, :show]
    resources :shortposts, only: [:index, :show]
    root "posts#index"
    devise_for :authors
    get 'category/:tag', to: 'posts#index', as: :tag

    namespace :admin do
      get '', to: 'posts#index'
      get '/category/:tag', to: 'posts#index', as: :tag
      resources :posts
      resources :shortposts
    end
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	validates :title, :excerpt, :body, presence: true
	validates :title, uniqueness: true
	validates :excerpt, length: { maximum: 400 }

	has_attached_file :category_image, styles: { medium: "300x300>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :category_image, content_type: /\Aimage\/.*\Z/
	#titles as urls
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
	#internationalization
	translates :title, :body, :excerpt
	#tagging
	acts_as_taggable
	#search
	searchkick
	#forum
	DISQUS_SHORTNAME = Rails.env == "development" ? "dev_shortname".freeze : "production_shortname".freeze
end

app/models/shortpost.rb
class Shortpost < ActiveRecord::Base
	validates :body, presence: true
	validates :body, length: { maximum: 200 }

	translates :body
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    
    before_action :authenticate_author!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def tag_cloud
      @tags = Post.tag_counts_on(:tags)
    end

    def index
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
        @shortposts = Shortpost.all
      elsif params[:query]
        @posts = Post.search(params[:query])
        @shortposts = Shortpost.all
      else
        @posts = Post.all.order('created_at desc')
        @shortposts = Shortpost.all
      end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to admin_path }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to admin_path }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to admin_path }
        format.json { head :no_content }
      end
    end

    def tab_cloud
      @tags = Post.tag_counts_on(:tags)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :created_at, :updated_at, :tag_list, :excerpt)
      end
  end
end

app/controllers/admin/shortposts_controller.rb
module Admin
  class ShortpostsController < ApplicationController
    before_action :set_shortpost, only: [:show, :edit, :update, :destroy]

    # GET /shortposts
    # GET /shortposts.json
    def index
      @shortposts = Shortpost.all
    end

    # GET /shortposts/1
    # GET /shortposts/1.json
    def show
    end

    # GET /shortposts/new
    def new
      @shortpost = Shortpost.new
    end

    # GET /shortposts/1/edit
    def edit
    end

    # POST /shortposts
    # POST /shortposts.json
    def create
      @shortpost = Shortpost.new(shortpost_params)

      respond_to do |format|
        if @shortpost.save
          format.html { redirect_to @shortpost, notice: 'Shortpost was successfully created.' }
          format.json { render :show, status: :created, location: @shortpost }
        else
          format.html { render :new }
          format.json { render json: @shortpost.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /shortposts/1
    # PATCH/PUT /shortposts/1.json
    def update
      respond_to do |format|
        if @shortpost.update(shortpost_params)
          format.html { redirect_to @shortpost, notice: 'Shortpost was successfully updated.' }
          format.json { render :show, status: :ok, location: @shortpost }
        else
          format.html { render :edit }
          format.json { render json: @shortpost.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /shortposts/1
    # DELETE /shortposts/1.json
    def destroy
      @shortpost.destroy
      respond_to do |format|
        format.html { redirect_to shortposts_url, notice: 'Shortpost was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_shortpost
        @shortpost = Shortpost.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def shortpost_params
        params.require(:shortpost).permit(:body)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	end

	def default_url_options(options={})
	  { locale: I18n.locale }
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show]

    # GET /posts
    # GET /posts.json
    def tag_cloud
      @tags = Post.tag_counts_on(:tags)
    end

    def index
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
                  .page(params[:page])
                  .paginate(page: params[:page], per_page: 5)
                  .order('created_at desc')
        
        @shortposts = Shortpost.all.shuffle[0..4]
        @posts_archive = Post.all.group_by { |t| t.created_at.beginning_of_month }
      elsif params[:query]
        @posts = Post.search(params[:query])
        
        @shortposts = Shortpost.all.shuffle[0..4]
        @posts_archive = Post.all.group_by { |t| t.created_at.beginning_of_month }
      else
        @posts = Post.all.order('created_at desc')
                  .paginate(page: params[:page], per_page: 5)
                  .order('created_at desc')
        
        @shortposts = Shortpost.all.shuffle[0..4]
        @posts_archive =  Post.all.order('created_at desc')
                                  .group_by { |t| t.created_at.beginning_of_month }
      end

    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @related_posts = Post.joins(:taggings)
                  .where('posts.id != ?', @post.id)
                  .where(taggings: { tag_id: @post.tag_ids })
                  .all.shuffle[0..3]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end
end

app/controllers/shortposts_controller.rb
class ShortpostsController < ApplicationController
  before_action :set_shortpost, only: [:show]

  # GET /shortposts
  # GET /shortposts.json
  def index
    @shortposts = Shortpost.all
  end

  # GET /shortposts/1
  # GET /shortposts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortpost
      @shortpost = Shortpost.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/shortposts_helper.rb
module ShortpostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for([:admin, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<form role="form">
  <div class="row">
    <div class="field form-group col-xs-6">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
      <div class="validation" id="validation-presence"></div>
    </div>
     <div class="field form-group col-xs-6">
      <%= f.label :tag_list, "Tags (separated by commas)" %> 
      <br>
      <%= f.text_field :tag_list, class: "form-control" %>
      <div class="validation" id="validation-presence"></div>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :excerpt %><br>
    <%= f.text_area :excerpt, class: "form-control", rows:"5" %>
    <div class="validation" id="validation-length"></div>
  </div>
  <div class="field form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 60, cols: 100  %>
  </div>
  <div class="row">
    <div class="field form-group col-xs-6">
      <%= f.label :created_at %><br>
      <%= f.date_select :created_at, class: "form-control" %>
    </div>
    <div class="field form-group col-xs-6">
      <%= f.label :updated_at %><br>
      <%= f.date_select :updated_at, class: "form-control" %>
    </div>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
</form>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', admin_path %>

app/views/admin/posts/index.html.erb
<div id="admin-list">

  <h4>
    <% if author_signed_in? %>
      Logged in as <strong><%= current_author.email %></strong>.
      <%= link_to "Logout", destroy_author_session_path, method: :delete  %>
     <% else %>
      <%= link_to "Login", new_author_session_path %>
    <% end %>
  </h4>

  <h1>Posts</h1>
  <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag, admin_tag_path(tag.name), class: css_class %>
  <% end %>

  <table class="table table-striped datatable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.tag_list.map { |t| link_to t, admin_tag_path(t)}.join(', ').html_safe %></td>
          <td><%= post.created_at.strftime("%Y %m %d") %></td>
          <td><%= post.updated_at.strftime("%Y %m %d") %></td>
          <td><%= link_to 'Show', post %> 
              <%= link_to 'Edit', edit_admin_post_path(post) %> 
              <%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_admin_post_path %>
  <br>
  <%= render 'admin/shortposts/index' %>
</div>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
	<strong>Category:</strong>
	<%= @post.tag_list %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @post.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @post.updated_at %>
</p>

<%= link_to 'Edit', edit_admin_post_path(@post) %> |
<%= link_to 'Back', admin_path %>

app/views/admin/shortposts/_form.html.erb
<%= form_for([:admin, @shortpost]) do |f| %>
  <% if @shortpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortpost.errors.count, "error") %> prohibited this shortpost from being saved:</h2>

      <ul>
      <% @shortpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/shortposts/_index.html.erb
<h1>Shortposts</h1>

<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>Body</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @shortposts.each do |shortpost| %>
      <tr>
        <td><%= shortpost.body.truncate(120) %></td>
        <td><%= link_to 'Show', shortpost %> 
            <%= link_to 'Edit', edit_admin_shortpost_path(shortpost) %>
            <%= link_to 'Destroy', admin_shortpost_path(shortpost), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortpost', new_admin_shortpost_path %>

app/views/admin/shortposts/edit.html.erb
<h1>Editing shortpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @shortpost %> |
<%= link_to 'Back', admin_path %>

app/views/admin/shortposts/new.html.erb
<h1>New shortpost</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/admin/shortposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @shortpost.body %>
</p>

<%= link_to 'Edit', edit_admin_shortpost_path(@shortpost) %> |
<%= link_to 'Back', admin %>

app/views/layouts/_archive.html.erb
<div id="archive">
	<% if I18n.locale == :hu %>
		<h3><span>Archív</span></h3>
	<% else %>
		<h3><span>Archive</span></h3>
	<% end %>

	<% @posts_archive.each do |month, posts| %>
		<div class="panel-group" id="accordion">
			<div class="panel panel-default">
				<div class="panel-heading">
		      <h4 class="panel-title">
		      	<a data-toggle="collapse" data-parent="#accordion" href="#<%= month.strftime('%B') %>">
							<%= "#{month.strftime('%B')} (#{posts.count}) "%>
						</a>
					</h4>
				</div>
				<div id="<%= month.strftime('%B')%>" class="panel-collapse collapse">
	      	<div class="panel-body">
	      		<ul class="list-unstyled">
							<% for post in posts %>
								<li><%= link_to post.title, post %></li>
							<% end %>
						</ul>
					</div>
		    </div>		
			</div>
		</div>
	<% end %>

app/views/layouts/_categories.html.erb
<div id="tags">
	<% if I18n.locale == :hu %>
		<h3><span>Kategóriák</span></h3>
		<% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
	    <%= link_to tag, tag_path(tag.name), class: css_class, id: tag.name, title: tag.name %>
		<% end %>
	<% else %>
		<h3><span>Categories</span></h3>
		<% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
	    <%= link_to tag, tag_path(tag.name), class: css_class, id: tag.name, title: tag.name %>
		<% end %>
	<% end %>
</div>

app/views/layouts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'foltyn'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>Foltyn</h1>
        <a href="mailto:bedafoltyn@gmail.com" target="_top">
          <%= image_tag("mail.png", height: "30", alt:"email")%>
        </a>
        <a href="https://github.com/bedafoltyn" target="_blank">
          <%= image_tag("github.png", height: "30", alt: "github") %>
        </a>
      </div>
      <div class="col-md-4">
        <ul class="list-unstyled">
          <% if I18n.locale == :hu %>
            <li><h3>Kategóriák</h3></li>
            <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
            <li>
              <%= link_to tag, tag_path(tag.name), class: css_class %>
            </li>
          <% end %>
          <% else %>
            <li><h3>Categories</h3></li>
            <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
            <li>
              <%= link_to tag, tag_path(tag.name), class: css_class %>
            </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-unstyled">
          <% if I18n.locale == :hu %>
            <li><h3>Oldalak</h3></li>
            <li><%= link_to "Főoldal", '/' %></li>
            <li><%= link_to "Rólam", page_path("about") %></li>
            <li><%= link_to "Hamarosan...", page_path("coming_soon") %></li>
          <% else %>
            <li><h3>Navigation</h3></li>
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "About", page_path("about") %></li>
            <li><%= link_to "Coming soon", page_path("coming_soon") %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-1">
        <div id="back-to-top">
          <span class="glyphicon glyphicon-arrow-up"></span>
        </div>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
		<div class="container">
			<div id="logo">
				<h1 class="pull-left">
					<% if I18n.locale == :hu %>
						<%= link_to "Foltyn", '/hu', id: "logo" %>
					<% else %>
						<%= link_to "Foltyn", '/en', id: "logo" %>
					<% end %>
				</h1>
			</div>
			<ul class="list-inline" id="menu">
				<% if I18n.locale == :hu %>
					<li>
						<h3><%= link_to "Rólam", page_path("about")%></h3>
					</li>
					<li>
						<h3><%= link_to "Hamarosan...", page_path("coming_soon")%></h3>
					</li>
				<% else %>
					<li>
						<h3><%= link_to "About", page_path("about")%></h3>
					</li>
					<li>
						<h3><%= link_to "Coming soon", page_path("coming_soon")%></h3>
					</li>
				<% end %>
				<li class="language">
					<% if I18n.locale == :hu %>
						<%= link_to(image_tag("en_red.png", height: "40",alt: "English", class: "language"), locale: "en") %>
					<% else %>
						<%= link_to_unless_current(image_tag("hu_red.png", height: "40",alt: "Magyar", class: "language"), locale: "hu") %>
					<% end %>
				</li>	
				<li id="search">
					<%= form_tag posts_path, method: :get do %>
				    <%= text_field_tag :query, params[:query] %>
				  <% end %>
				</li>
			</div>
		</div>
</header>

app/views/layouts/_posts.html.erb
<% @posts.each do |post| %>
		<div class="posts">
		  <h1><%= link_to post.title, post %></h1>
		  <p>
		  	<span class="glyphicon glyphicon-time"></span> 
		  	<%= post.created_at.strftime("%Y. %m. %d.") %>
		  </p>
		  <p>
		    <%= post.tag_list.map { |tag| link_to tag, tag_path(tag), class: "category-images", id: tag, title: tag }.join(' ').html_safe %>
		  </p>
		  <p><%= post.excerpt %></p>   
		</div>
	<% end %>

app/views/layouts/_shortposts.html.erb
<% @shortposts.each do |shortpost| %>
  <%= shortpost.body %></td>
<% end %>

app/views/layouts/_sidebar.html.erb
<aside>
	<%= render 'layouts/categories' %>
	<%= render 'layouts/archive' %>
	<div id="links">
		<% if I18n.locale == :hu %>
			<h3><span>Linkek</span></h3>
		<% else %>
			<h3><span>Links</span></h3>
		<% end %>
		<ul class="list-unstyled">
			<li><a href="http://theblackc000000de.blogspot.com">Brian's blog</li></a>
			<li><a href="http://rubynewbies.org/">Ruby Newbies</li></a>
			<li><a href="http://theodinproject.com/">The Odin Project</li></a>
			<li><a href="http://javascriptissexy.com/">Javascript.is(Sexy)</li></a>
			<li><a href="http://superherojs.com/">Superhero.js</a></li>
		</ul>
	</div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foltyn</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= google_webfonts_link_tag :roboto => 400,
 															 :bitter => 700,
 															 :special_elite => 400 %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div id="about">
	<% if I18n.locale == :hu %>
		<h1>Rólam</h1>
		<h2>Az oldalról</h2>
		<h3>Infók</h3>
		<p>Azért hoztam létre az oldalt, hogy dokumentáljam a tanulmányaimat, fejlesszem az írásomat angolul és magyarul egyaránt, illetve hogy gyakoroljak és fejlesszem a programozási képességeimet.</p>
		<p>A cikkek elsődlegesen nem tutorialnak készültek. 
			<span class="warning">Minden kódot a saját felelősségedre használj.</span> Minden javaslatot, javítást vagy esetleg kérést szívesen veszek.</p> 
			<p>De tényleg, javíts ki bármikor, azért vagyok itt, hogy tanuljak.</p>
		
		<h3>Technikai infók</h3>
		<p>A blog <strong>Ruby on Rails-el készült</strong> és <strong>Sass-t</strong> és <strong>Coffeescriptet</strong> használtam a frontenden. Itt a használt gemek listája:</p>
		<script src="https://gist.github.com/bedafoltyn/b9395baddb9c4a6aeb6d.js"></script>

		<h2>Rólam</h2>
		<br>
		<div class="col-md-8">
			<p>Frontend fejlesztő vagyok a karrierem legeslegelején. Szeretek új technológiákkal foglalkozni, kísérletezni velük és ezekkel létrehozni menő programokat. Szeretném fejleszteni a programozási képességemet backend és frontend részen egyaránt, programokat és weboldalakat készíteni, mindent amitől több leszek.</p> 
			<p>Az utazásomat a Ruby on Rails-el kezdtem, ami sajnos nem túl elterjedt itt, ahol élek, de ennek ellenére rengeteg mindenben segített, hogy megértsem a modern webfejlesztés alapjait és új technológiákat ismerhessek meg.</p> 
			<p>Nem lettem Rails fejlesztő, de nem is nagyon bánom, szeretem amit most csinálok és a Rails megmarad hobbinak továbbra is.</p>
		</div>
		<div class="col-md-4">
			<figure><img class="responsive" src="../../../../assets/logo.png" height="200"> </figure>
			<figcaption>Egy nagyon pontos kép rólam álruhában.</figcaption>
		</div>
	<% else %>	
		<h1>About</h1>
		
		<h2>The site</h2>
		<h3>Informations</h3>
		<p>I created this blog to document my studies, improve my writing skills both in English and in Hungarian, to practice and improve my programming skills.</p>
		<p>The posts are not intended to be tutorials. 
			<span class="warning">Use my code snippets on your own responsibility.</span> Suggestions, corrections, requests are welcomed.</p> 
			<p>But really, correct me anytime. I’m here to study.</p>
		
		<h3>Technical informations</h3>
		<p>The blog was built with <strong>Ruby on Rails</strong> and with <strong>Sass</strong> and <strong>Coffeescript</strong> on the front-end. Here are the gems I’ve used:</p>
		<script src="https://gist.github.com/bedafoltyn/b9395baddb9c4a6aeb6d.js"></script>

		<h2>Me</h2>
		<br>
		<div class="col-md-8">
			<p>I’m a junior front-end developer at the very beginning of my career. I’m passionate about learning new technologies, using them and creating something with them. I would like to improve both my frontend and backend programming skills, create programs, web sites, etc. </p>
			<p>I’ve started with Ruby on Rails, unfortunately it isn’t too “popular” in my country but it still helped me a lot to understand modern web developing methods and introduce me to new technologies (like Sass, Coffeescript, Haml, etc).</p> 
			<p>I didn’t become a Rails developer but it’s still my hobby to work with Rails.</p>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-4">
			<figure><img class="responsive" src="../../../../assets/logo.png" height="200"> </figure>
			<figcaption>A very accurate photo of me in disguise.</figcaption>
		</div>
	<% end %>	
</div>

app/views/posts/index.html.erb
<main>
	<%= render 'layouts/posts' %>
	<div class="text-center">
		<% if I18n.locale == :hu %>
			<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: 'Előző', next_label: 'Következő' %>
		<% else %>
			<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: 'Prev', next_label: 'Next' %>
		<% end %>
	</div>
</main>
<%= render 'layouts/sidebar'%>

app/views/posts/show.html.erb
<main>
	<div class="post">
		<h1>
		  <%= @post.title %>
		</h1>
		<p>
	  	<span class="glyphicon glyphicon-time"></span> 
	  	<%= @post.created_at.strftime("%Y. %m. %d.") %>
	  </p>
		<p>
			<%= @post.tag_list.map { |tag| link_to tag, tag_path(tag), class: "category-images", id: tag }.join(' ').html_safe %>
		</p>
		<p>
		  <%= raw @post.body %>
		</p>
	</div>
	<div class="recommended-posts">
		<% if I18n.locale == :hu %>
			<h3 class="recommended-title"><span>Ajánlott cikkek</span></h3>
		<% else %>
			<h3 class="recommended-title"><span>Recommended</span></h3>
		<% end %>	
		<% @related_posts.each do |post| %>
			<div class="recommended">
				<h3><%= link_to post.title, post %></h3>
				<p><%= post.excerpt.truncate(200, separator: " ") %></p>
			</div>
		<% end %>
	</div>
	<% if I18n.locale == :hu %>
		<h3>Kommentek</h3>
	<% else %>
		<h3>Comments</h3>
	<% end %>	
	<div class="comments">
	<%= render 'layouts/disqus' %>
	</div>
</main>
<aside class="hide-on-small">
	<% if I18n.locale == :hu %>
		<h3 class="recommended-title"><span>Ajánlott cikkek</span></h3>
	<% else %>
		<h3 class="recommended-title"><span>Recommended</span></h3>
	<% end %>	
	<% @related_posts.each do |post| %>
		<div class="recommended">
			<h3><%= link_to post.title, post %></h3>
			<p><%= post.excerpt.truncate(200, separator: " ") %></p>
		</div>
	<% end %>
</aside>

app/views/shortposts/index.html.erb
<% @shortposts.each do |shortpost| %>
  <div class="shortposts">
    <%= shortpost.body %></td>
  </div>
<% end %>

app/views/shortposts/show.html.erb
<%= @shortpost.body %>